//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationsLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OperationLibraryExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperationLibraryExceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OperationsLibrary.OperationLibraryExceptions", typeof(OperationLibraryExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression Not Found Error.
        /// </summary>
        internal static string EmptyExpression {
            get {
                return ResourceManager.GetString("EmptyExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Operand Type.
        /// </summary>
        internal static string InvalidOperandType {
            get {
                return ResourceManager.GetString("InvalidOperandType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Is Not Defined.
        /// </summary>
        internal static string InvalidOperatorException {
            get {
                return ResourceManager.GetString("InvalidOperatorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mismatched parentheses in expression. Insert a valid expression.
        /// </summary>
        internal static string MismatchedParentheses {
            get {
                return ResourceManager.GetString("MismatchedParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Enough Operands In Stack To Perform Operation.
        /// </summary>
        internal static string NotEnoughOperandsInStackToPerformOperation {
            get {
                return ResourceManager.GetString("NotEnoughOperandsInStackToPerformOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary operator must contain two operands only..
        /// </summary>
        internal static string OperandException {
            get {
                return ResourceManager.GetString("OperandException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator Class Not Found Exception.
        /// </summary>
        internal static string OperatorClassNotFoundException {
            get {
                return ResourceManager.GetString("OperatorClassNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Opertor Precedence. Value must be greater than 0..
        /// </summary>
        internal static string PrecedenceValueException {
            get {
                return ResourceManager.GetString("PrecedenceValueException", resourceCulture);
            }
        }
    }
}
